server {
    listen 80;
    listen [::]:80;
    server_name gymbro.spmbbanjarkab.web.id gymbro-backend.spmbbanjarkab.web.id;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/gymbro-acme;
        default_type text/plain;
    }
    location / {
        return 404;
    }
}
